/**
 * Configuration file for problem generation
 * Contains concept definitions and their generators
 *
 */

const CONFIG = {
  // Available concepts with their display names and subcategories
  AVAILABLE_CONCEPTS: {
    addition: {
      displayName: "Addition",
      category: "basic",
      subcategories: ["addition"],
      gradeAppropriate: [
        "Kindergarten",
        "1st Grade",
        "2nd Grade",
        "3rd Grade",
        "4th Grade",
        "5th Grade",
        "6th Grade",
        "7th Grade",
        "8th Grade",
        "9th Grade",
        "10th Grade",
        "11th Grade",
        "12th Grade",
      ],
      estimatedTimeSeconds: {
        1: 10,
        2: 15,
        3: 22,
        4: 30,
        5: 40,
      },
    },
    subtraction: {
      displayName: "Subtraction",
      category: "basic",
      subcategories: ["subtraction"],
      gradeAppropriate: [
        "Kindergarten",
        "1st Grade",
        "2nd Grade",
        "3rd Grade",
        "4th Grade",
        "5th Grade",
        "6th Grade",
        "7th Grade",
        "8th Grade",
        "9th Grade",
        "10th Grade",
        "11th Grade",
        "12th Grade",
      ],
      estimatedTimeSeconds: {
        1: 10,
        2: 15,
        3: 22,
        4: 30,
        5: 40,
      },
    },
    multiplication: {
      displayName: "Multiplication",
      category: "basic",
      subcategories: ["multiplication"],
      gradeAppropriate: [
        "3rd Grade",
        "4th Grade",
        "5th Grade",
        "6th Grade",
        "7th Grade",
        "8th Grade",
        "9th Grade",
        "10th Grade",
        "11th Grade",
        "12th Grade",
      ],
      estimatedTimeSeconds: {
        1: 10,
        2: 15,
        3: 22,
        4: 30,
        5: 40,
      },
    },
    division: {
      displayName: "Division",
      category: "basic",
      subcategories: ["division"],
      gradeAppropriate: [
        "3rd Grade",
        "4th Grade",
        "5th Grade",
        "6th Grade",
        "7th Grade",
        "8th Grade",
        "9th Grade",
        "10th Grade",
        "11th Grade",
        "12th Grade",
      ],
      estimatedTimeSeconds: {
        1: 10,
        2: 15,
        3: 22,
        4: 30,
        5: 40,
      },
    },
    fraction: {
      displayName: "Fraction",
      category: "basic",
      subcategories: ["fractionaddition", "fractionsubtraction"],
      gradeAppropriate: [
        "3rd Grade",
        "4th Grade",
        "5th Grade",
        "6th Grade",
        "7th Grade",
        "8th Grade",
        "9th Grade",
        "10th Grade",
        "11th Grade",
        "12th Grade",
      ],
      estimatedTimeSeconds: {
        1: 10,
        2: 15,
        3: 22,
        4: 30,
        5: 40,
      },
    },
    mixedArithmetic: {
      displayName: "Multi-Step Problems",
      category: "mixed",
      subcategories: ["mixedArithmetic"],
      gradeAppropriate: [
        "3rd Grade",
        "4th Grade",
        "5th Grade",
        "6th Grade",
        "7th Grade",
        "8th Grade",
        "9th Grade",
        "10th Grade",
        "11th Grade",
        "12th Grade",
      ],
      estimatedTimeSeconds: {
        1: 20,
        2: 30,
        3: 40,
        4: 50,
        5: 60,
      },
    },
  },
};

module.exports = CONFIG;
